swagger: "2.0"
info:
  title: "Exam Cell Automaton API"
  version: "1.0.0"
  contact:
    name: Felix Orinda
    email: forinda82@gmail.com
basePath: /api/v1
host: localhost:6200
schemes:
  - http
  - https
tags:
  - name: Metadata
    description: Metadata related requests
